M48
; DRILL file {KiCad 9.0.1-9.0.1-0~ubuntu24.10.1} date 2025-04-24T18:54:53+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-24T18:54:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1-9.0.1-0~ubuntu24.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X163.003Y-126.65
X163.003Y-132.43
M30
